package com.niit.vay.config;

public enum Status {
    NEW_USER,
    NEW_GUEST,
    OAUTH2_USER_NOT_REGISTERED,
    FAILED_AUTHENTICATION,
    ALREADY_REGISTERED,
    ACCOUNT_TO_ACTIVATE,
    ACCOUNT_ACTIVATED_SUCCESSFULLY,
    USERNAME_TAKEN,
    INVALID_PASSWORD,
    PASSWORD_RESET_MAIL_SENT
}
